#ddev-generated
services:
  db-mssql:
    container_name: ddev-${DDEV_SITENAME}-db-mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
       - 1433:1433
    environment:
      # https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2017
      MSSQL_SA_PASSWORD: "belloQuesto100"
      ACCEPT_EULA: "Y"
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    # https://github.com/ddev/ddev-contrib/tree/master/docker-compose-services/sqlsrv
    volumes:
    - ".:/mnt/ddev_config"
    # - mssqldata:/var/opt/mssql/

  db-mssql-scripter:
    container_name: ddev-${DDEV_SITENAME}-db-mssql-scripter
    build: 
      context: .
      dockerfile: Dockerfile.mssql-scripter
    entrypoint: ["tail", "-f", "/dev/null"]
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    # healthcheck:
    #   disable: true
    # init: false
    # scale: 0
    volumes:
    - ".:/mnt/ddev_config"
    links:
    - db-mssql:db-mssql

  web:
    links:
    - db-mssql:db-mssql

# volumes:
# -  mssqldata: